package com.bihu.carcontrol.common.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bihu.carcontrol.common.greendao.db.RadioBean;
import com.bihu.carcontrol.common.greendao.db.MaintainBean;

import com.bihu.carcontrol.common.greendao.db.RadioBeanDao;
import com.bihu.carcontrol.common.greendao.db.MaintainBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig radioBeanDaoConfig;
    private final DaoConfig maintainBeanDaoConfig;

    private final RadioBeanDao radioBeanDao;
    private final MaintainBeanDao maintainBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        radioBeanDaoConfig = daoConfigMap.get(RadioBeanDao.class).clone();
        radioBeanDaoConfig.initIdentityScope(type);

        maintainBeanDaoConfig = daoConfigMap.get(MaintainBeanDao.class).clone();
        maintainBeanDaoConfig.initIdentityScope(type);

        radioBeanDao = new RadioBeanDao(radioBeanDaoConfig, this);
        maintainBeanDao = new MaintainBeanDao(maintainBeanDaoConfig, this);

        registerDao(RadioBean.class, radioBeanDao);
        registerDao(MaintainBean.class, maintainBeanDao);
    }
    
    public void clear() {
        radioBeanDaoConfig.clearIdentityScope();
        maintainBeanDaoConfig.clearIdentityScope();
    }

    public RadioBeanDao getRadioBeanDao() {
        return radioBeanDao;
    }

    public MaintainBeanDao getMaintainBeanDao() {
        return maintainBeanDao;
    }

}
