package com.bihu.carcontrol.common.greendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MAINTAIN_BEAN".
 */
@Entity
public class MaintainBean {

    @Id
    private Long id;
    private String description;
    private Long timestamp;
    private Boolean isMaintainTimeSet;
    private Long maintainTimeSetTime;
    private Integer maintainTimeSetValue;
    private Boolean isMaintainMileageSet;
    private Long maintainMileageSetTime;
    private Integer maintainMileageSetValue;

    @Generated
    public MaintainBean() {
    }

    public MaintainBean(Long id) {
        this.id = id;
    }

    @Generated
    public MaintainBean(Long id, String description, Long timestamp, Boolean isMaintainTimeSet, Long maintainTimeSetTime, Integer maintainTimeSetValue, Boolean isMaintainMileageSet, Long maintainMileageSetTime, Integer maintainMileageSetValue) {
        this.id = id;
        this.description = description;
        this.timestamp = timestamp;
        this.isMaintainTimeSet = isMaintainTimeSet;
        this.maintainTimeSetTime = maintainTimeSetTime;
        this.maintainTimeSetValue = maintainTimeSetValue;
        this.isMaintainMileageSet = isMaintainMileageSet;
        this.maintainMileageSetTime = maintainMileageSetTime;
        this.maintainMileageSetValue = maintainMileageSetValue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Boolean getIsMaintainTimeSet() {
        return isMaintainTimeSet;
    }

    public void setIsMaintainTimeSet(Boolean isMaintainTimeSet) {
        this.isMaintainTimeSet = isMaintainTimeSet;
    }

    public Long getMaintainTimeSetTime() {
        return maintainTimeSetTime;
    }

    public void setMaintainTimeSetTime(Long maintainTimeSetTime) {
        this.maintainTimeSetTime = maintainTimeSetTime;
    }

    public Integer getMaintainTimeSetValue() {
        return maintainTimeSetValue;
    }

    public void setMaintainTimeSetValue(Integer maintainTimeSetValue) {
        this.maintainTimeSetValue = maintainTimeSetValue;
    }

    public Boolean getIsMaintainMileageSet() {
        return isMaintainMileageSet;
    }

    public void setIsMaintainMileageSet(Boolean isMaintainMileageSet) {
        this.isMaintainMileageSet = isMaintainMileageSet;
    }

    public Long getMaintainMileageSetTime() {
        return maintainMileageSetTime;
    }

    public void setMaintainMileageSetTime(Long maintainMileageSetTime) {
        this.maintainMileageSetTime = maintainMileageSetTime;
    }

    public Integer getMaintainMileageSetValue() {
        return maintainMileageSetValue;
    }

    public void setMaintainMileageSetValue(Integer maintainMileageSetValue) {
        this.maintainMileageSetValue = maintainMileageSetValue;
    }

}
