package com.bihu.carcontrol.common.greendao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RADIO_BEAN".
 */
@Entity
public class RadioBean {

    @Id
    private Long id;
    private String name;
    private Integer frequency;

    @Generated
    public RadioBean() {
    }

    public RadioBean(Long id) {
        this.id = id;
    }

    @Generated
    public RadioBean(Long id, String name, Integer frequency) {
        this.id = id;
        this.name = name;
        this.frequency = frequency;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

}
