class VehiclePropertyGroup:
    SYSTEM      = 0x10000000
    VENDOR      = 0x20000000
    MASK        = 0xf0000000

class VehiclePropertyType:
    STRING          = 0x00100000
    BOOLEAN         = 0x00200000
    INT32           = 0x00400000
    INT32_VEC       = 0x00410000
    INT64           = 0x00500000
    INT64_VEC       = 0x00510000
    FLOAT           = 0x00600000
    FLOAT_VEC       = 0x00610000
    BYTES           = 0x00700000
    MIXED           = 0x00e00000
    MASK            = 0x00ff0000

class VehicleArea:
    GLOBAL      = 0x01000000
    WINDOW      = 0x03000000
    MIRROR      = 0x04000000
    SEAT        = 0x05000000
    DOOR        = 0x06000000
    WHEEL       = 0x07000000
    MASK        = 0x0f000000

variables = {
    "INFO_VIN" :        0x0100        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.STRING        | VehicleArea.GLOBAL,
    "INFO_MAKE" :        0x0101        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.STRING        | VehicleArea.GLOBAL,
    "INFO_MODEL" :        0x0102        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.STRING        | VehicleArea.GLOBAL,
    "INFO_MODEL_YEAR" :        0x0103        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "INFO_FUEL_CAPACITY" :        0x0104        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "INFO_FUEL_TYPE" :        0x0105        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "INFO_EV_BATTERY_CAPACITY" :        0x0106        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "INFO_EV_CONNECTOR_TYPE" :        0x0107        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "INFO_FUEL_DOOR_LOCATION" :        0x0108        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "INFO_EV_PORT_LOCATION" :        0x0109        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "INFO_DRIVER_SEAT" :        0x010A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "INFO_EXTERIOR_DIMENSIONS" :        0x010B        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "INFO_MULTI_EV_PORT_LOCATIONS" :        0x010C        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "PERF_ODOMETER" :        0x0204        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "PERF_VEHICLE_SPEED" :        0x0207        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "PERF_VEHICLE_SPEED_DISPLAY" :        0x0208        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "PERF_STEERING_ANGLE" :        0x0209        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "PERF_REAR_STEERING_ANGLE" :        0x0210        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "ENGINE_COOLANT_TEMP" :        0x0301        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "ENGINE_OIL_LEVEL" :        0x0303        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "ENGINE_OIL_TEMP" :        0x0304        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "ENGINE_RPM" :        0x0305        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "WHEEL_TICK" :        0x0306        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT64_VEC        | VehicleArea.GLOBAL,
    "FUEL_LEVEL" :        0x0307        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "FUEL_DOOR_OPEN" :        0x0308        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "EV_BATTERY_LEVEL" :        0x0309        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "EV_CHARGE_PORT_OPEN" :        0x030A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "EV_CHARGE_PORT_CONNECTED" :        0x030B        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "EV_BATTERY_INSTANTANEOUS_CHARGE_RATE" :        0x030C        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "RANGE_REMAINING" :        0x0308        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "TIRE_PRESSURE" :        0x0309        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.WHEEL,
    "CRITICALLY_LOW_TIRE_PRESSURE" :        0x030A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.WHEEL,
    "GEAR_SELECTION" :        0x0400        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "CURRENT_GEAR" :        0x0401        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "PARKING_BRAKE_ON" :        0x0402        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "PARKING_BRAKE_AUTO_APPLY" :        0x0403        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "FUEL_LEVEL_LOW" :        0x0405        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "NIGHT_MODE" :        0x0407        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "TURN_SIGNAL_STATE" :        0x0408        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "IGNITION_STATE" :        0x0409        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "ABS_ACTIVE" :        0x040A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "TRACTION_CONTROL_ACTIVE" :        0x040B        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "HVAC_FAN_SPEED" :        0x0500        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "HVAC_FAN_DIRECTION" :        0x0501        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "HVAC_TEMPERATURE_CURRENT" :        0x0502        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.SEAT,
    "HVAC_TEMPERATURE_SET" :        0x0503        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.SEAT,
    "HVAC_DEFROSTER" :        0x0504        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.WINDOW,
    "HVAC_AC_ON" :        0x0505        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_MAX_AC_ON" :        0x0506        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_MAX_DEFROST_ON" :        0x0507        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_RECIRC_ON" :        0x0508        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_DUAL_ON" :        0x0509        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_AUTO_ON" :        0x050A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_SEAT_TEMPERATURE" :        0x050B        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "HVAC_SIDE_MIRROR_HEAT" :        0x050C        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.MIRROR,
    "HVAC_STEERING_WHEEL_HEAT" :        0x050D        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HVAC_TEMPERATURE_DISPLAY_UNITS" :        0x050E        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HVAC_ACTUAL_FAN_SPEED_RPM" :        0x050F        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "HVAC_POWER_ON" :        0x0510        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_FAN_DIRECTION_AVAILABLE" :        0x0511        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.SEAT,
    "HVAC_AUTO_RECIRC_ON" :        0x0512        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "HVAC_SEAT_VENTILATION" :        0x0513        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "HVAC_ELECTRIC_DEFROSTER_ON" :        0x0514        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.WINDOW,
    "HVAC_TEMPERATURE_VALUE_SUGGESTION" :        0x0515        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT_VEC        | VehicleArea.GLOBAL,
    "DISTANCE_DISPLAY_UNITS" :        0x0600        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "FUEL_VOLUME_DISPLAY_UNITS" :        0x0601        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "TIRE_PRESSURE_DISPLAY_UNITS" :        0x0602        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "EV_BATTERY_DISPLAY_UNITS" :        0x0603        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "FUEL_CONSUMPTION_UNITS_DISTANCE_OVER_VOLUME" :        0x0604        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "VEHICLE_SPEED_DISPLAY_UNITS" :        0x0605        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "EPOCH_TIME" :        0x0606        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT64        | VehicleArea.GLOBAL,
    "STORAGE_ENCRYPTION_BINDING_SEED" :        0x0607        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BYTES        | VehicleArea.GLOBAL,
    "ENV_OUTSIDE_TEMPERATURE" :        0x0703        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "AP_POWER_STATE_REQ" :        0x0A00        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "AP_POWER_STATE_REPORT" :        0x0A01        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "AP_POWER_BOOTUP_REASON" :        0x0A02        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "DISPLAY_BRIGHTNESS" :        0x0A03        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HW_KEY_INPUT" :        0x0A10        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "HW_ROTARY_INPUT" :        0x0A20        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "HW_CUSTOM_INPUT" :        0X0A30        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "DOOR_POS" :        0x0B00        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.DOOR,
    "DOOR_MOVE" :        0x0B01        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.DOOR,
    "DOOR_LOCK" :        0x0B02        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.DOOR,
    "MIRROR_Z_POS" :        0x0B40        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.MIRROR,
    "MIRROR_Z_MOVE" :        0x0B41        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.MIRROR,
    "MIRROR_Y_POS" :        0x0B42        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.MIRROR,
    "MIRROR_Y_MOVE" :        0x0B43        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.MIRROR,
    "MIRROR_LOCK" :        0x0B44        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "MIRROR_FOLD" :        0x0B45        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "SEAT_MEMORY_SELECT" :        0x0B80        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_MEMORY_SET" :        0x0B81        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_BELT_BUCKLED" :        0x0B82        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.SEAT,
    "SEAT_BELT_HEIGHT_POS" :        0x0B83        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_BELT_HEIGHT_MOVE" :        0x0B84        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_FORE_AFT_POS" :        0x0B85        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_FORE_AFT_MOVE" :        0x0B86        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_BACKREST_ANGLE_1_POS" :        0x0B87        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_BACKREST_ANGLE_1_MOVE" :        0x0B88        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_BACKREST_ANGLE_2_POS" :        0x0B89        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_BACKREST_ANGLE_2_MOVE" :        0x0B8A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_HEIGHT_POS" :        0x0B8B        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_HEIGHT_MOVE" :        0x0B8C        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_DEPTH_POS" :        0x0B8D        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_DEPTH_MOVE" :        0x0B8E        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_TILT_POS" :        0x0B8F        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_TILT_MOVE" :        0x0B90        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_LUMBAR_FORE_AFT_POS" :        0x0B91        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_LUMBAR_FORE_AFT_MOVE" :        0x0B92        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_LUMBAR_SIDE_SUPPORT_POS" :        0x0B93        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_LUMBAR_SIDE_SUPPORT_MOVE" :        0x0B94        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_HEADREST_HEIGHT_POS" :        0x0B95        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "SEAT_HEADREST_HEIGHT_MOVE" :        0x0B96        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_HEADREST_ANGLE_POS" :        0x0B97        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_HEADREST_ANGLE_MOVE" :        0x0B98        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_HEADREST_FORE_AFT_POS" :        0x0B99        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_HEADREST_FORE_AFT_MOVE" :        0x0B9A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SEAT_OCCUPANCY" :        0x0BB0        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "WINDOW_POS" :        0x0BC0        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.WINDOW,
    "WINDOW_MOVE" :        0x0BC1        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.WINDOW,
    "WINDOW_LOCK" :        0x0BC4        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.WINDOW,
    "VEHICLE_MAP_SERVICE" :        0x0C00        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "OBD2_LIVE_FRAME" :        0x0D00        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "OBD2_FREEZE_FRAME" :        0x0D01        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "OBD2_FREEZE_FRAME_INFO" :        0x0D02        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "OBD2_FREEZE_FRAME_CLEAR" :        0x0D03        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "HEADLIGHTS_STATE" :        0x0E00        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HIGH_BEAM_LIGHTS_STATE" :        0x0E01        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "FOG_LIGHTS_STATE" :        0x0E02        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HAZARD_LIGHTS_STATE" :        0x0E03        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HEADLIGHTS_SWITCH" :        0x0E10        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HIGH_BEAM_LIGHTS_SWITCH" :        0x0E11        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "FOG_LIGHTS_SWITCH" :        0x0E12        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "HAZARD_LIGHTS_SWITCH" :        0x0E13        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "CABIN_LIGHTS_STATE" :        0x0F01        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "CABIN_LIGHTS_SWITCH" :        0x0F02        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "READING_LIGHTS_STATE" :        0x0F03        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "READING_LIGHTS_SWITCH" :        0x0F04        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32        | VehicleArea.SEAT,
    "SUPPORT_CUSTOMIZE_VENDOR_PERMISSION" :        0x0F05        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "DISABLED_OPTIONAL_FEATURES" :        0x0F06        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.STRING        | VehicleArea.GLOBAL,
    "INITIAL_USER_INFO" :        0x0F07        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "SWITCH_USER" :        0x0F08        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "CREATE_USER" :        0x0F09        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "REMOVE_USER" :        0x0F0A        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "USER_IDENTIFICATION_ASSOCIATION" :        0x0F0B        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "EVS_SERVICE_REQUEST" :        0x0F10        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "POWER_POLICY_REQ" :        0x0F21        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.STRING        | VehicleArea.GLOBAL,
    "POWER_POLICY_GROUP_REQ" :        0x0F22        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.STRING        | VehicleArea.GLOBAL,
    "CURRENT_POWER_POLICY" :        0x0F23        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.STRING        | VehicleArea.GLOBAL,
    "WATCHDOG_ALIVE" :        0xF31        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.INT64        | VehicleArea.GLOBAL,
    "WATCHDOG_TERMINATED_PROCESS" :        0x0F32        | VehiclePropertyGroup.SYSTEM        | VehiclePropertyType.MIXED        | VehicleArea.GLOBAL,
    "VHAL_HEARTBEAT" :         0x0F33         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.INT64         | VehicleArea.GLOBAL,
    "CLUSTER_SWITCH_UI" :         0x0F34         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.INT32         | VehicleArea.GLOBAL,
    "CLUSTER_DISPLAY_STATE" :         0x0F35         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.INT32_VEC         | VehicleArea.GLOBAL,
    "CLUSTER_REPORT_STATE" :         0x0F36         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.MIXED         | VehicleArea.GLOBAL,
    "CLUSTER_REQUEST_DISPLAY" :         0x0F37         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.INT32         | VehicleArea.GLOBAL,
    "CLUSTER_NAVIGATION_STATE" :         0x0F38         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.BYTES         | VehicleArea.GLOBAL,
    "ELECTRONIC_TOLL_COLLECTION_CARD_TYPE" :         0x0F39         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.INT32         | VehicleArea.GLOBAL,
    "ELECTRONIC_TOLL_COLLECTION_CARD_STATUS" :         0x0F3A         | VehiclePropertyGroup.SYSTEM         | VehiclePropertyType.INT32         | VehicleArea.GLOBAL,
    "GECKO_EV_CHARGE_TIME_REMAINING" :        0x2000        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_EV_BATTERY_VOLTAGE" :        0x2001        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_EV_BATTERY_CURRENT" :        0x2002        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_VEHICLE_DRIVE_MODE" :        0x2003        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_MOMER_MAX_VOLTCELL" :        0x2004        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_MOMER_MIN_VOLTCELL" :        0x2005        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_MOMER_MAX_TEMPCELL" :        0x2006        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_MOMER_MIN_TEMPCELL" :        0x2007        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_GLOBAL_ANNOUNCEMENT" :        0x2008        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32_VEC        | VehicleArea.GLOBAL,
    "GECKO_AVERAGE_ENERGY_CONSUMPTION" :        0x2009        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_INSTANCE_ENERGY_CONSUMPTION" :        0x200A        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_LAMPLET_STATUS" :        0x200B        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_MAIN_SEAT_PRESSURE_STATUS" :        0x200C        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_BRAKE_LEVEL_ALARM_STATUS" :        0x200D        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_MAIN_SEAT_SAFETY_BELT_STATUS" :        0x200E        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_ENGINE_STATUS" :        0x200F        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_LOW_VOL_BATTERY_VOL" :        0x2010        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_CLTC_RANGE_REMAINING" :        0x2011        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.FLOAT        | VehicleArea.GLOBAL,
    "GECKO_ENGINE_TEMP" :        0x2012        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_ENGINE_STATE" :        0x2013        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_HVAC_PTC_HEAT_ON" :        0x2014        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.BOOLEAN        | VehicleArea.GLOBAL,
    "GECKO_HIGH_BEAM_LIGHTS_LEVEL" :        0x2015        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,    
    "GECKO_HVAC_CONTROL_ERROR" :        0x2016        | VehiclePropertyGroup.VENDOR        | VehiclePropertyType.INT32        | VehicleArea.GLOBAL,
    "GECKO_CCM_SPEED_LIMIT_LEVEL" :                0x20EC | VehiclePropertyGroup.VENDOR | VehiclePropertyType.INT32 | VehicleArea.GLOBAL,
    "GECKO_VCU_CHRG_SOC_TAR_SP" :                0x20ED | VehiclePropertyGroup.VENDOR | VehiclePropertyType.INT32 | VehicleArea.GLOBAL,
    "GECKO_VCU_FAULT_CODE" :                0x20EE | VehiclePropertyGroup.VENDOR | VehiclePropertyType.INT32 | VehicleArea.GLOBAL,
}

for var, value in variables.items():
#    print(f"{var}: {value}")
    print "{}: {}".format(var, value)


