/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.1.0 Mon Jun 19 15:23:58 2023.
 */

#include <string.h>

#include "chassise_can_ccm_4_0.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int chassise_can_ccm_4_0_gw_acu_133_pack(
    uint8_t *dst_p,
    const struct chassise_can_ccm_4_0_gw_acu_133_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->acu_gsensor_fault, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->acu_system_sts, 3u, 0x38u);
    dst_p[0] |= pack_left_shift_u8(src_p->acu_airb_warn_lamp_st, 1u, 0x06u);
    dst_p[0] |= pack_left_shift_u8(src_p->acu_crash_outp_sts, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->acu_livecounter_0x133, 4u, 0x30u);
    dst_p[7] |= pack_left_shift_u8(src_p->acu_checksum_0x133, 0u, 0x0fu);

    return (8);
}

int chassise_can_ccm_4_0_gw_acu_133_unpack(
    struct chassise_can_ccm_4_0_gw_acu_133_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->acu_gsensor_fault = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->acu_system_sts = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->acu_airb_warn_lamp_st = unpack_right_shift_u8(src_p[0], 1u, 0x06u);
    dst_p->acu_crash_outp_sts = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->acu_livecounter_0x133 = unpack_right_shift_u8(src_p[7], 4u, 0x30u);
    dst_p->acu_checksum_0x133 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

uint8_t chassise_can_ccm_4_0_gw_acu_133_acu_gsensor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_acu_133_acu_gsensor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_acu_133_acu_gsensor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_gw_acu_133_acu_system_sts_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_acu_133_acu_system_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_acu_133_acu_system_sts_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t chassise_can_ccm_4_0_gw_acu_133_acu_airb_warn_lamp_st_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_acu_133_acu_airb_warn_lamp_st_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_acu_133_acu_airb_warn_lamp_st_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t chassise_can_ccm_4_0_gw_acu_133_acu_crash_outp_sts_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_acu_133_acu_crash_outp_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_acu_133_acu_crash_outp_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_gw_acu_133_acu_livecounter_0x133_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_acu_133_acu_livecounter_0x133_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_acu_133_acu_livecounter_0x133_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t chassise_can_ccm_4_0_gw_acu_133_acu_checksum_0x133_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_acu_133_acu_checksum_0x133_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_acu_133_acu_checksum_0x133_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int chassise_can_ccm_4_0_gw_abs_171_pack(
    uint8_t *dst_p,
    const struct chassise_can_ccm_4_0_gw_abs_171_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->abs_abs_fail_status, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->abs_llivecounter_0x171, 4u, 0x30u);
    dst_p[7] |= pack_left_shift_u8(src_p->abs_checksum_0x171, 0u, 0x0fu);

    return (8);
}

int chassise_can_ccm_4_0_gw_abs_171_unpack(
    struct chassise_can_ccm_4_0_gw_abs_171_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->abs_abs_fail_status = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->abs_llivecounter_0x171 = unpack_right_shift_u8(src_p[7], 4u, 0x30u);
    dst_p->abs_checksum_0x171 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

uint8_t chassise_can_ccm_4_0_gw_abs_171_abs_abs_fail_status_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_abs_171_abs_abs_fail_status_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_abs_171_abs_abs_fail_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_gw_abs_171_abs_llivecounter_0x171_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_abs_171_abs_llivecounter_0x171_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_abs_171_abs_llivecounter_0x171_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t chassise_can_ccm_4_0_gw_abs_171_abs_checksum_0x171_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_gw_abs_171_abs_checksum_0x171_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_gw_abs_171_abs_checksum_0x171_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int chassise_can_ccm_4_0_eps_300_pack(
    uint8_t *dst_p,
    const struct chassise_can_ccm_4_0_eps_300_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[6] |= pack_left_shift_u8(src_p->eps_run_state, 0u, 0x03u);
    dst_p[7] |= pack_left_shift_u8(src_p->eps_livecounter_0x300, 4u, 0x30u);
    dst_p[7] |= pack_left_shift_u8(src_p->eps_checksum_0x300, 0u, 0x0fu);

    return (8);
}

int chassise_can_ccm_4_0_eps_300_unpack(
    struct chassise_can_ccm_4_0_eps_300_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->eps_run_state = unpack_right_shift_u8(src_p[6], 0u, 0x03u);
    dst_p->eps_livecounter_0x300 = unpack_right_shift_u8(src_p[7], 4u, 0x30u);
    dst_p->eps_checksum_0x300 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

uint8_t chassise_can_ccm_4_0_eps_300_eps_run_state_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_300_eps_run_state_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_300_eps_run_state_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t chassise_can_ccm_4_0_eps_300_eps_livecounter_0x300_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_300_eps_livecounter_0x300_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_300_eps_livecounter_0x300_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t chassise_can_ccm_4_0_eps_300_eps_checksum_0x300_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_300_eps_checksum_0x300_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_300_eps_checksum_0x300_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int chassise_can_ccm_4_0_eps_301_pack(
    uint8_t *dst_p,
    const struct chassise_can_ccm_4_0_eps_301_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->eps_motor_curr_flt, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_motor_volt_flt, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_torq_snr_s_sig_out_rng_flt, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_torq_snr_p_sig_out_rng_flt, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_torq_snr_t1_t2_sig_sync_flt, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_torq_snr_t1_sig_out_rng_flt, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_torq_snr_t2_sig_out_rng_flt, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->eps_torq_snr5_v_flt, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_can_bus_flt, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_over_volt_flt, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_under_volt_flt, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_uncalibrated_angle_flt, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_over_heat_flt, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_relay_flt, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_motor_curr_fellow_flt, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->eps_motor_drv_flt, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->eps_vcu_time_out_flt, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->eps_livecounter_0x301, 4u, 0x30u);
    dst_p[7] |= pack_left_shift_u8(src_p->eps_checksum_0x301, 0u, 0x0fu);

    return (8);
}

int chassise_can_ccm_4_0_eps_301_unpack(
    struct chassise_can_ccm_4_0_eps_301_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->eps_motor_curr_flt = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->eps_motor_volt_flt = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->eps_torq_snr_s_sig_out_rng_flt = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->eps_torq_snr_p_sig_out_rng_flt = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->eps_torq_snr_t1_t2_sig_sync_flt = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->eps_torq_snr_t1_sig_out_rng_flt = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->eps_torq_snr_t2_sig_out_rng_flt = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->eps_torq_snr5_v_flt = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->eps_can_bus_flt = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->eps_over_volt_flt = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->eps_under_volt_flt = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->eps_uncalibrated_angle_flt = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->eps_over_heat_flt = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->eps_relay_flt = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->eps_motor_curr_fellow_flt = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->eps_motor_drv_flt = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->eps_vcu_time_out_flt = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->eps_livecounter_0x301 = unpack_right_shift_u8(src_p[7], 4u, 0x30u);
    dst_p->eps_checksum_0x301 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_motor_curr_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_motor_curr_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_motor_curr_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_motor_volt_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_motor_volt_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_motor_volt_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_torq_snr_s_sig_out_rng_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_torq_snr_s_sig_out_rng_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_torq_snr_s_sig_out_rng_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_torq_snr_p_sig_out_rng_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_torq_snr_p_sig_out_rng_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_torq_snr_p_sig_out_rng_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_torq_snr_t1_t2_sig_sync_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_torq_snr_t1_t2_sig_sync_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_torq_snr_t1_t2_sig_sync_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_torq_snr_t1_sig_out_rng_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_torq_snr_t1_sig_out_rng_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_torq_snr_t1_sig_out_rng_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_torq_snr_t2_sig_out_rng_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_torq_snr_t2_sig_out_rng_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_torq_snr_t2_sig_out_rng_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_torq_snr5_v_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_torq_snr5_v_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_torq_snr5_v_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_can_bus_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_can_bus_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_can_bus_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_over_volt_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_over_volt_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_over_volt_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_under_volt_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_under_volt_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_under_volt_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_uncalibrated_angle_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_uncalibrated_angle_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_uncalibrated_angle_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_over_heat_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_over_heat_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_over_heat_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_relay_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_relay_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_relay_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_motor_curr_fellow_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_motor_curr_fellow_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_motor_curr_fellow_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_motor_drv_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_motor_drv_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_motor_drv_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_vcu_time_out_flt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_vcu_time_out_flt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_vcu_time_out_flt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_livecounter_0x301_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_livecounter_0x301_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_livecounter_0x301_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t chassise_can_ccm_4_0_eps_301_eps_checksum_0x301_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_eps_301_eps_checksum_0x301_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_eps_301_eps_checksum_0x301_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int chassise_can_ccm_4_0_abs_420_pack(
    uint8_t *dst_p,
    const struct chassise_can_ccm_4_0_abs_420_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->abs_wheel_speed_fr_no_signal_err, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->abs_wheel_speed_fr_interm_err, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->abs_wheel_speed_fr_open_short_err, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->abs_wheel_speed_fl_no_signal_err, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->abs_wheel_speed_fl_interm_err, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->abs_wheel_speed_fl_open_short_err, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->abs_power_undervolt, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->abs_power_overvolt, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_valve_relay_err, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_wheel_speed_freq_err, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_wheel_speed_rr_no_signal_err, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_wheel_speed_rr_interm_err, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_wheel_speed_rr_open_short_err, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_wheel_speed_rl_no_signal_err, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_wheel_speed_rl_interm_err, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_wheel_speed_rl_open_short_err, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_outlet_valve_rr_err, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_inlet_valve_rr_err, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_outlet_valve_rl_err, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_inlet_valve_rl_err, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_outlet_valve_fr_err, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_inlet_valve_fr_err, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_outlet_valve_fl_err, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->abs_inlet_valve_fl_err, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->abs_current_max_fault_level, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->abs_can_bus_off_err, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->abs_can_hardware_err, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->abs_ecu_hardware_err, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->abs_motor_relay_err, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->abs_motor_err, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->abs_valve_err, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->abs_livecounter_0x420, 4u, 0x30u);
    dst_p[7] |= pack_left_shift_u8(src_p->abs_checksum_0x420, 0u, 0x0fu);

    return (8);
}

int chassise_can_ccm_4_0_abs_420_unpack(
    struct chassise_can_ccm_4_0_abs_420_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->abs_wheel_speed_fr_no_signal_err = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->abs_wheel_speed_fr_interm_err = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->abs_wheel_speed_fr_open_short_err = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->abs_wheel_speed_fl_no_signal_err = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->abs_wheel_speed_fl_interm_err = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->abs_wheel_speed_fl_open_short_err = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->abs_power_undervolt = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->abs_power_overvolt = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->abs_valve_relay_err = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->abs_wheel_speed_freq_err = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->abs_wheel_speed_rr_no_signal_err = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->abs_wheel_speed_rr_interm_err = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->abs_wheel_speed_rr_open_short_err = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->abs_wheel_speed_rl_no_signal_err = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->abs_wheel_speed_rl_interm_err = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->abs_wheel_speed_rl_open_short_err = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->abs_outlet_valve_rr_err = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->abs_inlet_valve_rr_err = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->abs_outlet_valve_rl_err = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->abs_inlet_valve_rl_err = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->abs_outlet_valve_fr_err = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->abs_inlet_valve_fr_err = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->abs_outlet_valve_fl_err = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->abs_inlet_valve_fl_err = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->abs_current_max_fault_level = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->abs_can_bus_off_err = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->abs_can_hardware_err = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->abs_ecu_hardware_err = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->abs_motor_relay_err = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->abs_motor_err = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->abs_valve_err = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->abs_livecounter_0x420 = unpack_right_shift_u8(src_p[7], 4u, 0x30u);
    dst_p->abs_checksum_0x420 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_no_signal_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_no_signal_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_no_signal_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_interm_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_interm_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_interm_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_open_short_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_open_short_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fr_open_short_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_no_signal_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_no_signal_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_no_signal_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_interm_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_interm_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_interm_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_open_short_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_open_short_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_fl_open_short_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_power_undervolt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_power_undervolt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_power_undervolt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_power_overvolt_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_power_overvolt_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_power_overvolt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_valve_relay_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_valve_relay_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_valve_relay_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_freq_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_freq_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_freq_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_no_signal_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_no_signal_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_no_signal_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_interm_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_interm_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_interm_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_open_short_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_open_short_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rr_open_short_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_no_signal_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_no_signal_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_no_signal_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_interm_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_interm_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_interm_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_open_short_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_open_short_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_wheel_speed_rl_open_short_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_outlet_valve_rr_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_outlet_valve_rr_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_outlet_valve_rr_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_inlet_valve_rr_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_inlet_valve_rr_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_inlet_valve_rr_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_outlet_valve_rl_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_outlet_valve_rl_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_outlet_valve_rl_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_inlet_valve_rl_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_inlet_valve_rl_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_inlet_valve_rl_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_outlet_valve_fr_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_outlet_valve_fr_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_outlet_valve_fr_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_inlet_valve_fr_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_inlet_valve_fr_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_inlet_valve_fr_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_outlet_valve_fl_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_outlet_valve_fl_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_outlet_valve_fl_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_inlet_valve_fl_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_inlet_valve_fl_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_inlet_valve_fl_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_current_max_fault_level_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_current_max_fault_level_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_current_max_fault_level_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_can_bus_off_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_can_bus_off_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_can_bus_off_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_can_hardware_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_can_hardware_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_can_hardware_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_ecu_hardware_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_ecu_hardware_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_ecu_hardware_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_motor_relay_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_motor_relay_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_motor_relay_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_motor_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_motor_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_motor_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_valve_err_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_valve_err_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_valve_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_livecounter_0x420_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_livecounter_0x420_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_livecounter_0x420_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t chassise_can_ccm_4_0_abs_420_abs_checksum_0x420_encode(double value)
{
    return (uint8_t)(value);
}

double chassise_can_ccm_4_0_abs_420_abs_checksum_0x420_decode(uint8_t value)
{
    return ((double)value);
}

bool chassise_can_ccm_4_0_abs_420_abs_checksum_0x420_is_in_range(uint8_t value)
{
    return (value <= 15u);
}
